### ISSUE TITLE
Separate extensions with their own specific file name

### ISSUE THREAD

**Issue by coder-Aayush** [AbhishekDoshi26/super_extensions#13]
Separate extension in their own file name

example 
context_extension.dart
num_extension.dart
.....

**Comment by AbhishekDoshi26** [comment]
@coder-Aayush yep. this is needed. if you want, you can start working on this. 

Warning: #11 will be a breaking change and you might need to refactor many things later.

If you wish to work on it, feel free to assign the issue to yourself and move ahead 🚀

**Comment by AbhishekDoshi26** [comment]
Fixed with #16
