### ISSUE TITLE
Issue package publish to pub.dev

### ISSUE THREAD

**Issue by CoderNamedHendrick** [AbhishekDoshi26/super_extensions#25]
I noticed the package isn't available on pub.dev while there's a publish task in the actions. Could we investigate the problem.

**Comment by AbhishekDoshi26** [comment]
Hey @CoderNamedHendrick. Yes it's not published to pub.dev because I still have to write an example for the package #7

**Comment by AbhishekDoshi26** [comment]
Package has been published: https://pub.dev/packages/super_extensions
Thanks to all the contributors!
