### ISSUE TITLE
Enum extension

### ISSUE THREAD

**Issue by anubhavbagri** [AbhishekDoshi26/super_extensions#28]
I wanted to know whether a lot of folks have faced this issue: While sending data as payload to an API endpoint [for eg. in a POST request] sometimes an enum is required which should be in `Upper case` as well as `Snake case` [in case a particular enum value contains more than one word]

But, according to the [dart linter](https://dart-lang.github.io/linter/lints/constant_identifier_names.html) :

> PREFER using lowerCamelCase for constant names.
> In new code, use lowerCamelCase for constant variables, including enum values.

Hence I had made this small getter extension which return `string` to solve the above stated particular usecase:

```
extension EnumExtension on Enum {
  String get value {
    return name.splitMapJoin(
      RegExp('(?<=[a-z])(?=[A-Z])'),
      onMatch: (m) => '_${m.group(0)}',
      onNonMatch: (n) => n.toUpperCase(),
    );
  }
}
```

Example:

```
enum ReportType {
  spam,
  scamOrFraud,
}

/// Verified on https://www.dartpad.dev/
ReportType.scamOrFraud.value -> SCAM_OR_FRAUD[in string]
ReportType.spam.value -> SPAM [in string]
```

If this feels like a necessity, it could be included in this package! 🎉

**Comment by AbhishekDoshi26** [comment]
Hey @anubhavbagri thanks for filing this issue. I haven't encountered this problem. Mainly because with new rules, enums can be created with camelCase. And when I want to pass it to the API, if it is needed in upperCase, I usually use `.name.toUpperCase()`.

Also, with enhanced enums as part of Dart 2.17, this won't really feel like a necessity. Let me know your thoughts :)

**Comment by anubhavbagri** [comment]
Hey @AbhishekDoshi26, I believe I'm running the latest dart version but still I get this warning when I use `Snake case`

![image](https://user-images.githubusercontent.com/56643117/236836243-f1763682-cbe2-42d1-a0b4-12c89acf49f5.png)

```
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (3 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1
```

Please correct me, if I'm wrong 😅

**Comment by AbhishekDoshi26** [comment]
Yes. You can't use this. You need to use lowerCamelCase. SnakeCases are not allowed. As I mentioned, camelcases are allowed in names. I feel, even for the payloads, the BE should accept lowerCamelCase as that's the standart one.

**Comment by anubhavbagri** [comment]
In my situation, the backend wasn't accepting lowerCamelCase hence I came up with this!

No worries! Thanks for the clarification
