### ISSUE TITLE
Add Example Project

### ISSUE THREAD

**Issue by AbhishekDoshi26** [AbhishekDoshi26/super_extensions#7]
Inside the package, add an example application that uses all the extensions.

**Comment by AbhishekDoshi26** [comment]
@jakansha2001 would you like to take this?

**Comment by jakansha2001** [comment]
Sure. I will do it.

**Comment by CoderNamedHendrick** [comment]
Doesn't seem like there's a PR for this Issue yet.

Can I take it up @AbhishekDoshi26

**Comment by AbhishekDoshi26** [comment]
@CoderNamedHendrick thanks for the willingness to contribute. I really appreciate it. Let's wait. @jakansha2001 is working on it. She is new to open-source so will take some time 😉
