### ISSUE TITLE
Unit tests for extension methods

### ISSUE THREAD

**Issue by CoderNamedHendrick** [AbhishekDoshi26/super_extensions#9]
I see there are no unit tests being run on the project currently. While testing extensions on build-context might be tricky, the ones on standard types should be feasible.

**Comment by AbhishekDoshi26** [comment]
Hey @CoderNamedHendrick yes. Unit-Tests would be good to have. Would you like to create a PR for the same?

**Comment by CoderNamedHendrick** [comment]
Sure!!! Working on them right away.

**Comment by AbhishekDoshi26** [comment]
Assigned the issue to you :)

**Comment by CoderNamedHendrick** [comment]
#11

**Comment by AbhishekDoshi26** [comment]
Issue resolved with #11
